### ISSUE TITLE
PyPI Wheels for Python 3.10

### ISSUE THREAD

**Issue by XuehaiPan** [zephyrproject-rtos/windows-curses#26]
Hi, the default stable version of Python 3 has been updated to 3.10 since 2021/10/04 (see [Active Python Releases](https://www.python.org/downloads)). However, `windows-curses` cannot install with `pip` on Python 3.10.

```console
# PanXuehai @ Windows-11-VM in ~ [15:54:35]
$ Get-Command -All python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         3.10.150.… C:\Tools\Python3\python.exe
Application     python.exe                                         0.0.0.0    C:\Users\PanXuehai\AppData\Local\Microsoft\WindowsApps\python.exe


# PanXuehai @ Windows-11-VM in ~ [15:54:48]
$ python --version
Python 3.10.0


# PanXuehai @ Windows-11-VM in ~ [15:55:00]
$ Get-Command -All pip

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pip.exe                                            0.0.0.0    C:\Tools\Python3\Scripts\pip.exe


# PanXuehai @ Windows-11-VM in ~ [15:55:10]
$ pip install windows-curses
ERROR: Could not find a version that satisfies the requirement windows-curses (from versions: none)
ERROR: No matching distribution found for windows-curses
```

**Comment by mglmc** [comment]
Same here

**Comment by MartyMacGyver** [comment]
Between this and #27 I've taken an initial stab at this problem but haven't made much progress due to significant changes in the Python 3.10 ABI.

First though, a quick how to build `windows-curses` for Windows 10 Python 3.9 (x64) from scratch

Install Python 3.9 (x64) with the "py launcher" option (e.g. the Windows installer (64-bit) from https://www.python.org/downloads/release/python-398/)

Install Python 3.10 (x64) as well (e.g. the Windows installer (64-bit) from https://www.python.org/downloads/release/python-3100/)

Install VS2017 or VS2019 (both seem to work fine, VS2022 might work as well?)
  - Select "Python development"
  - In the Installation details to the right, under Python development / Optional:
    - UN-check "Python 3 64-bit" (we already have 3.9 and 3.10)
    - Check "Python native development tools"

Git clone https://github.com/zephyrproject-rtos/windows-curses

open "x64 Native Tools Command Prompt for VS 2017"

To build for Python 3.9 (verifying that everything you've installed works), use:

    cd /d \YOUR\PATH\TO\THE\REPO\windows-curses
    build-wheels.bat 3.9

-----

To attempt Python 3.10, I created the `py310` folder following the py39 folder structure:

https://github.com/MartyMacGyver/windows-curses/tree/mff-py310

As a baseline, I took the same four source files directly from Python tag `v3.10.0` (https://github.com/python/cpython/tree/v3.10.0/Modules) unmodified:
* `_curses_panel.c`
* `_cursesmodule.c`
* `clinic/_curses_panel.c.h`
* `clinic/_cursesmodule.c.h`

When I ran `build-wheels.bat 3.10` there were immediate problems:

* The new _cursesmodule.c includes:
    #include "pycore_long.h"          // _PyLong_GetZero()
    #include "pycore_structseq.h"     // PyStructSequence_InitType()
* However, these lines (new to py310) refer to internal headers, causing the build to throw the error "this header requires Py_BUILD_CORE define"
* You can't use Py_BUILD_CORE as it's ONLY usable when building the CPython itself (as notes in https://devguide.python.org/c-api/)
* This wasn't a problem in 3.9 and earlier - it's not simply a matter of applying existing patches, but working around the ABI changes themselves

I post this in case it helps others who care to delve into this problem as well. It appears it would be highly non-trivial to build this CPython curses code as part of an external module... I wonder if it'd make more sense to divorce this from the Python core code entirely if it's diverging this significantly?
