### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by danielhrisca** [zephyrproject-rtos/windows-curses#6]
I get this error when I try to install on Python 3.8 (Python 3.8.0b4 (tags/v3.8.0b4:d93605d, Aug 29 2019, 23:21:28) [MSC v.1916 64 bit (AMD64)] on win32):

``ERROR: windows_curses-2.0.1-cp38-cp38m-win_amd64.whl is not a supported wheel on this platform.``

**Comment by ulfalizer** [comment]
I think I built the Python 3.8 wheels against beta 3. I wonder if something changed to make them incompatible. My Windows VM died today due to disk corruption, so might take a few days before I can look into it.

If you have time, you could check if the wheels works with beta 3 on your machine. Would be interesting to know.

**Comment by danielhrisca** [comment]
Yes, it working with Python 3.8 beta 3

**Comment by ulfalizer** [comment]
> Yes, it working with Python 3.8 beta 3

Ah, alright, probably just needs a rebuild in that case. Weird that compatibility broke between two betas though. Don't see anything relevant in the changelogs.

I'll update it as soon as I have a working Windows again. Thanks for checking.

**Comment by ulfalizer** [comment]
Rebuilt against the just-released non-beta Python 3.8 now. Works fine from local testing.
